language: cpp

matrix:
  fast_finish: true
  include:
    - stage: test
    - os: linux
      dist: bionic
      compiler: gcc
      name: bionic-gcc
      env: ISOLATED=true
    - os: linux
      dist: xenial
      compiler: gcc
      name: xenial-gcc
      env: ISOLATED=true
    - os: linux
      dist: bionic
      compiler: clang
      name: bionic-clang
      env: ISOLATED=true
    - os: linux
      dist: xenial
      compiler: clang
      name: xenial-clang
      env: ISOLATED=true
    - os: windows
      compiler: gcc
      name: windows-gcc
      env: ISOLATED=true

  allow_failures:
    - os: windows
      compiler: gcc
      name: windows-gcc
      env: ISOLATED=true

addons:
  apt:
    packages:
      - libglfw3-dev 
      - libglfw3 
      - libxcursor-dev 
      - libglm-dev
      - libpthread-stubs0-dev
      - libxi-dev
      - libxxf86vm-dev 
      - libx11-xcb-dev
      - libxau-dev
      - libxdmcp-dev
      - libx11-dev
      - libxinerama-dev
      - libglu1-mesa-dev
      - libxrandr-dev

install: 
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install glfw3; fi;

before_script:
  - git clone https://github.com/nothings/stb.git include/stb

script:
  - mkdir -p build 
  - cd build
  - cmake ..
  - make -j2

cache:
  directories:
    - build

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: build/main.out
  file_glob: true
  skip_cleanup: true
  on:
    tags: true