language: cpp

dist: bionic

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install libglfw3-dev libglfw3 libxcursor-dev libglm-dev -y

before_script:
  - git clone https://github.com/nothings/stb.git include/stb

script:
  - mkdir build && cd build
  - cmake ..
  - make -j2

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: build/main.out
  file_glob: true
  skip_cleanup: true
  on:
    tags: true