language: cpp

stages:
  - should work
  - deploy

matrix:
  fast_finish: true
  include:
    - stage: should work
      os: linux
      dist: bionic
      compiler: gcc
      name: linux-bionic-gcc
      addons:
        apt:
          packages:
            - libxcursor-dev 
            - libpthread-stubs0-dev
            - libxi-dev
            - libxxf86vm-dev 
            - libx11-xcb-dev
            - libxau-dev
            - libxdmcp-dev
            - libx11-dev
            - libxinerama-dev
            - libglu1-mesa-dev
            - libxrandr-dev
            - xorg-dev
      script: bash .Travis/build_linux.sh "${TRAVIS_JOB_NAME}"
      env: ISOLATED=true
    - stage: should work
      os: linux
      dist: bionic
      compiler: clang
      name: linux-bionic-clang
      addons:
        apt:
          packages:
            - libxcursor-dev 
            - libpthread-stubs0-dev
            - libxi-dev
            - libxxf86vm-dev 
            - libx11-xcb-dev
            - libxau-dev
            - libxdmcp-dev
            - libx11-dev
            - libxinerama-dev
            - libglu1-mesa-dev
            - libxrandr-dev
            - xorg-dev
      script: bash .Travis/build_linux.sh "${TRAVIS_JOB_NAME}"
      env: ISOLATED=true
    - stage: should work
      os: linux
      dist: xenial
      compiler: gcc
      name: linux-xenial-gcc
      addons:
        apt:
          packages:
            - libxcursor-dev 
            - libpthread-stubs0-dev
            - libxi-dev
            - libxxf86vm-dev 
            - libx11-xcb-dev
            - libxau-dev
            - libxdmcp-dev
            - libx11-dev
            - libxinerama-dev
            - libglu1-mesa-dev
            - libxrandr-dev
            - xorg-dev
      script: bash .Travis/build_linux.sh "${TRAVIS_JOB_NAME}"
      env: ISOLATED=true
    - stage: should work
      os: linux
      dist: xenial
      compiler: clang
      name: linux-xenial-clang
      addons:
        apt:
          packages:
            - libxcursor-dev 
            - libpthread-stubs0-dev
            - libxi-dev
            - libxxf86vm-dev 
            - libx11-xcb-dev
            - libxau-dev
            - libxdmcp-dev
            - libx11-dev
            - libxinerama-dev
            - libglu1-mesa-dev
            - libxrandr-dev
            - xorg-dev
      script: bash .Travis/build_linux.sh "${TRAVIS_JOB_NAME}"
      env: ISOLATED=true
    - stage: should work
      os: windows
      compiler: gcc
      name: windows-gcc
      script: bash .Travis/build_windows.sh "${TRAVIS_JOB_NAME}" "gitbash"
      env: ISOLATED=true


install: skip

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: deploy/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
