language: cpp

stages:
  - should work
  - deploy

matrix:
  fast_finish: true
  include:
    - stage: should work
      os: linux
      dist: bionic
      compiler: gcc
      name: linux-bionic-gcc
      addons:
        apt:
          packages:
            - xorg-dev
      install: skip
      script: bash scripts/build_linux.sh "${TRAVIS_JOB_NAME}"
      env: ISOLATED=true
    - stage: should work
      os: linux
      dist: bionic
      compiler: clang
      name: linux-bionic-clang
      addons:
        apt:
          packages:
            - xorg-dev
      install: skip
      script: bash scripts/build_linux.sh "${TRAVIS_JOB_NAME}"
      env: ISOLATED=true
    - stage: should work
      os: windows
      compiler: gcc
      name: windows-gcc
      install: 
        - choco install git-lfs
        - choco install mingw
        - choco install make
      script: bash scripts/build_windows.sh "${TRAVIS_JOB_NAME}" "gitbash"
      env: ISOLATED=true

script_install:
  - git lfs pull


deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: deploy/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
