language: cpp

cache: ccache

matrix:
  include:
    - stage: should work
      os: linux
      dist: bionic
      compiler: gcc
      name: bionic-gcc
      addons:
        apt:
          packages:
            - libglfw3-dev 
            - libglfw3 
            - libxcursor-dev 
            - libpthread-stubs0-dev
            - libxi-dev
            - libxxf86vm-dev 
            - libx11-xcb-dev
            - libxau-dev
            - libxdmcp-dev
            - libx11-dev
            - libxinerama-dev
            - libglu1-mesa-dev
            - libxrandr-dev
      script: bash .Travis/build_linux.sh
      cache:
        directories:
          - build
      env: ISOLATED=true
    - stage: should work
      os: linux
      dist: bionic
      compiler: clang
      name: bionic-clang
      addons:
        apt:
          packages:
            - libglfw3-dev 
            - libglfw3 
            - libxcursor-dev 
            - libpthread-stubs0-dev
            - libxi-dev
            - libxxf86vm-dev 
            - libx11-xcb-dev
            - libxau-dev
            - libxdmcp-dev
            - libx11-dev
            - libxinerama-dev
            - libglu1-mesa-dev
            - libxrandr-dev
      script: bash .Travis/build_linux.sh
      cache:
        directories:
          - build
      env: ISOLATED=true
    - stage: should work
      os: linux
      dist: xenial
      compiler: gcc
      name: xenial-gcc
      addons:
        apt:
          packages:
            - libglfw3-dev 
            - libglfw3 
            - libxcursor-dev 
            - libpthread-stubs0-dev
            - libxi-dev
            - libxxf86vm-dev 
            - libx11-xcb-dev
            - libxau-dev
            - libxdmcp-dev
            - libx11-dev
            - libxinerama-dev
            - libglu1-mesa-dev
            - libxrandr-dev
      script: bash .Travis/build_linux.sh
      cache:
        directories:
          - build
      env: ISOLATED=true
    - stage: should work
      os: linux
      dist: xenial
      compiler: clang
      name: xenial-clang
      addons:
        apt:
          packages:
            - libglfw3-dev 
            - libglfw3 
            - libxcursor-dev 
            - libpthread-stubs0-dev
            - libxi-dev
            - libxxf86vm-dev 
            - libx11-xcb-dev
            - libxau-dev
            - libxdmcp-dev
            - libx11-dev
            - libxinerama-dev
            - libglu1-mesa-dev
            - libxrandr-dev
      script: bash .Travis/build_linux.sh
      cache:
        directories:
          - build
      env: ISOLATED=true
    - stage: experimental
      os: windows
      compiler: gcc
      name: windows-gcc
      script: bash .Travis/build_windows.sh
      cache:
        directories:
          - build
      env: ISOLATED=true
      
  fast_finish: true
  allow_failures:
    - stage: experimental
      os: windows
      compiler: gcc
      name: windows-gcc
      script: bash .Travis/build_windows.sh
      cache:
        directories:
          - build
      env: ISOLATED=true


install: skip

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: build/main.out
  file_glob: true
  skip_cleanup: true
  on:
    tags: true