language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: windows

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libglfw3-dev 
      - libglfw3 
      - libxcursor-dev 
      - libglm-dev

install: skip

before_script:
  - git clone https://github.com/nothings/stb.git include/stb

script:
  - mkdir -p build 
  - cd build
  - cmake ..
  - make -j2

cache:
  directories:
    - build

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: build/main.out
  file_glob: true
  skip_cleanup: true
  on:
    tags: true