name: C/C++ CI

on: [push]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [gcc, clang]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run:  bash scripts/dependencies.sh
    - name: setup the project
      run:  bash scripts/setup.sh
    - name: build
      env:  
          BUILDNAME: $(git rev-list HEAD --count)
      run:  bash scripts/build.sh -j 2 -o $BUILDNAME
