name: CI

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [clang]
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    
    steps:
    - uses: actions/checkout@v1
      with: 
        lfs: false
    - name: add required ppa
      run: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt update
      if: matrix.os == 'ubuntu-latest'
    - name: install dependencies
      run:  bash scripts/dependencies.sh --ci
    - name: setup the project
      run:  bash scripts/setup.sh --ci
    - name: build library
      run:  bash scripts/build.sh -j 2 -o $GITHUB_SHA
    - name: build testgame
      run:  bash testgame/scripts/build.sh -j 2 -o "testgame-$GITHUB_SHA"
    - uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: build-artifact-${{ matrix.os }}
        path: .
