name: C/C++ CI

on: [push]

jobs:
  build:

    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: ./scripts/dependencies.sh
    - name: build
      run: ./scripts/build.sh
