name: C/C++ CI

on: [push]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [gcc, clang]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run:  bash scripts/dependencies.sh
    - name: build
      run:  bash scripts/build.sh
